# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: API Container Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install smoke deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Build API image
        run: |
          docker build -f apps/api/Dockerfile -t ytd-api:ci .

      - name: Run API container
        run: |
          docker run -d --rm -p 8000:8000 --name ytd-api ytd-api:ci

      - name: Wait for API to be ready
        run: |
          for i in {1..60}; do
            if curl -sf http://127.0.0.1:8000/healthz > /dev/null; then
              echo "API is ready in iteration $i"; break; fi; sleep 2; done
          curl -v http://127.0.0.1:8000/healthz || (echo 'Health check failed' && docker logs ytd-api && exit 1)

      - name: Run observability smoke
        run: |
          python scripts/smoke_observability.py http://127.0.0.1:8000

      - name: Container logs (on failure)
        if: failure()
        run: |
          docker logs ytd-api || true

      - name: Stop container
        if: always()
        run: |
          docker stop ytd-api || true
