# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Observability Smoke

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          pip install requests

      - name: Start API
        run: |
          nohup python -m uvicorn apps.api.aurora.main:app --host 127.0.0.1 --port 8000 --log-level warning &
          for i in {1..60}; do
            curl -sf http://127.0.0.1:8000/healthz && break || sleep 1;
          done

      - name: Smoke observability
        run: |
          python scripts/smoke_observability.py http://127.0.0.1:8000
