name: RAG Golden Harness

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-golden:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run RAG golden harness
        run: |
          python scripts/ci_rag_harness.py
