# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tenant Retrieval Smoke (optional)

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'Run heavy tenant smoke (1 to enable)'
        required: false
        default: '0'
  push:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - 'scripts/**'
      - '.github/workflows/tenant-retrieval-smoke.yml'

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      RUN_TENANT_SMOKE: '0'

    services:
      meilisearch:
        image: getmeili/meilisearch:v1.7
        ports:
          - 7700:7700
        env:
          MEILI_NO_ANALYTICS: 'true'
      qdrant:
        image: qdrant/qdrant:v1.8.2
        ports:
          - 6333:6333

    steps:
      - uses: actions/checkout@v4
      - name: Wait for Meilisearch and Qdrant
        run: |
          echo "Waiting for Meilisearch (http://localhost:7700/health) and Qdrant (http://localhost:6333/collections)"
          for i in {1..60}; do
            MS=0; QD=0
            curl -fsS http://localhost:7700/health >/dev/null && MS=1 || true
            curl -fsS http://localhost:6333/collections >/dev/null && QD=1 || true
            if [ "$MS" = "1" ] && [ "$QD" = "1" ]; then
              echo "Services are up"; break; fi
            echo "Wait $i..."; sleep 1;
          done
          curl -fsS http://localhost:7700/health >/dev/null
          curl -fsS http://localhost:6333/collections >/dev/null

      - name: Enable run gate on dispatch
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run != '' }}
        run: echo "RUN_TENANT_SMOKE=${{ github.event.inputs.run }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        env:
          PYTHONPATH: .
        run: |
          if [ "${RUN_TENANT_SMOKE}" != "1" ] && [ "${RUN_TENANT_SMOKE}" != "true" ]; then echo "Skipping install (gate off)"; exit 0; fi
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Seed tenants (clean start)
        env:
          PYTHONPATH: .
          MEILI_URL: http://localhost:7700
          QDRANT_URL: http://localhost:6333
          AURORA_DEFAULT_TENANT_ID: 1
        run: |
          if [ "${RUN_TENANT_SMOKE}" != "1" ] && [ "${RUN_TENANT_SMOKE}" != "true" ]; then echo "Skipping seed (gate off)"; exit 0; fi
          source .venv/bin/activate
          RESET_MEILI=1 RESET_QDRANT_ALL=1 AURORA_DEFAULT_TENANT_ID=1 python scripts/index_documents.py
          AURORA_DEFAULT_TENANT_ID=1 python scripts/index_documents.py
          AURORA_DEFAULT_TENANT_ID=2 python scripts/index_documents.py

      - name: Run tenant retrieval smoke (script)
        env:
          PYTHONPATH: .
          MEILI_URL: http://localhost:7700
          QDRANT_URL: http://localhost:6333
          AURORA_DEFAULT_TENANT_ID: 1
        run: |
          if [ "${RUN_TENANT_SMOKE}" != "1" ] && [ "${RUN_TENANT_SMOKE}" != "true" ]; then echo "Skipping script (gate off)"; exit 0; fi
          source .venv/bin/activate
          python scripts/smoke_retrieval_tenants.py

      - name: Run pytest wrapper (optional)
        env:
          PYTHONPATH: .
          MEILI_URL: http://localhost:7700
          QDRANT_URL: http://localhost:6333
          AURORA_RUN_TENANT_SMOKE: '1'
          AURORA_DEFAULT_TENANT_ID: 1
        run: |
          if [ "${RUN_TENANT_SMOKE}" != "1" ] && [ "${RUN_TENANT_SMOKE}" != "true" ]; then echo "Skipping pytest (gate off)"; exit 0; fi
          source .venv/bin/activate
          pytest -q apps/api/tests/test_api_tenant_retrieval.py
